#! /bin/bash

echo  " Inicialização do processo "
echo  " Criando diretórios "

mkdir /publico
mkdir /adm
mkdir /ven
mkdir /s

echo  " Criando grupos "

groupadd GRP_ADM
agrupar adicionar GRP_VEN
groupadd GRP_SEC

echo  " Alterando permissões dos diretórios "

chown -R root:GRP_ADM /adm
chown -R root:GRP_VEN /ven
chown -R root:GRP_SEC /seg

echo  " Criando usuários "

useradd carlos -c " Carlos " -s /bin/bash -m -g GRP_ADM
passwd carlos -e
useradd maria -c " Maria " -s /bin/bash -m -g GRP_ADM
senha maria -e
useradd joao -c " João " -s /bin/bash -m -g GRP_ADM
passwd joao -e
useradd debora -c " Debora " -s /bin/bash -m -g GRP_VEN
passwd debora -e
useradd sebastiana -c " Sebastiana " -s /bin/bash -m -g GRP_VEN
senha sebastiana -e
useradd roberto -c " Roberto " -s /bin/bash -m -g GRP_VEN
passwd roberto -e
useradd josefina -c " Josefina " -s /bin/bash -m -g GRP_SEC
senha josefina -e
useradd amanda -c " Amanda " -s /bin/bash -m -g GRP_SEC
senha amanda -e
useradd rogerio -c " Rogerio " -s /bin/bash -m -g GRP_SEC
passwd rogerio -e

chmod 777 /publico -R
chmod 770 /adm
chmod 770 /ven
chmod 770 /s

echo  " Finalizado "
